#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"

trap 'kill -- -$$' INT TERM

pip install -e .
./example_project/manage.py migrate --noinput
./example_project/manage.py collectstatic --noinput
./example_project/manage.py runserver "$@" &
sleep 2
./aimmo_game_creator/service.py &

wait
